'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, BedDouble, Building2, Check, ChevronRight, Mail, MapPin, Menu, Phone, Ruler, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

export const properties = [
  { id: 1, title: 'Villa am See', location: 'Starnberg, München', type: 'Villa', price: '2.480.000 €', rooms: 7, area: 285, image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85' },
  { id: 2, title: 'Penthouse Maximilian', location: 'Altstadt, Düsseldorf', type: 'Penthouse', price: '1.890.000 €', rooms: 4, area: 172, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85' },
  { id: 3, title: 'Townhouse Elbchaussee', location: 'Blankenese, Hamburg', type: 'Haus', price: '1.240.000 €', rooms: 5, area: 198, image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85' },
  { id: 4, title: 'Loft am Paul-Lincke-Ufer', location: 'Kreuzberg, Berlin', type: 'Wohnung', price: '895.000 €', rooms: 3, area: 118, image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85' },
  { id: 5, title: 'Landhaus mit Weitblick', location: 'Grünwald, München', type: 'Haus', price: '3.200.000 €', rooms: 8, area: 340, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85' },
  { id: 6, title: 'Residenz an der Alster', location: 'Harvestehude, Hamburg', type: 'Wohnung', price: '1.670.000 €', rooms: 4, area: 154, image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85' },
]

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/92 backdrop-blur-xl">
    <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10">
      <Link href="/" className="group flex items-center gap-3"><span className="flex size-9 items-center justify-center border border-foreground text-sm font-semibold">N</span><span className="font-serif text-lg tracking-[0.12em]">NORDHAUS <span className="font-sans text-[10px] tracking-[0.2em] text-muted-foreground">IMMOBILIEN</span></span></Link>
      <nav className="hidden items-center gap-8 text-sm md:flex"><Link className="transition-colors hover:text-accent-foreground" href="/#finden">Immobilie finden</Link><Link className="transition-colors hover:text-accent-foreground" href="/verkaufen">Immobilie verkaufen</Link><Link className="transition-colors hover:text-accent-foreground" href="/#ueber-uns">Über uns</Link></nav>
      <Button variant="outline" className="hidden rounded-none border-foreground px-5 md:flex" asChild><a href="tel:+49891234567">Gespräch vereinbaren <Phone data-icon="inline-end" /></a></Button>
      <button aria-label="Menü öffnen" onClick={() => setOpen(!open)} className="md:hidden"><Menu /></button>
    </div>
    {open && <nav className="flex flex-col gap-5 border-t border-border px-6 py-5 text-sm md:hidden"><Link href="/#finden" onClick={() => setOpen(false)}>Immobilie finden</Link><Link href="/verkaufen" onClick={() => setOpen(false)}>Immobilie verkaufen</Link><Link href="/#ueber-uns" onClick={() => setOpen(false)}>Über uns</Link></nav>}
  </header>
}

export function Footer() { return <footer className="border-t border-border bg-foreground text-background"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-14 md:grid-cols-[1.5fr_1fr_1fr] lg:px-10"><div><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center border border-background text-sm font-semibold">N</span><span className="font-serif text-lg tracking-[0.12em]">NORDHAUS</span></div><p className="mt-5 max-w-xs text-sm leading-6 text-background/60">Immobilien mit Haltung. Wir begleiten Menschen und Werte seit über 15 Jahren.</p></div><div><p className="mb-4 text-xs uppercase tracking-[0.2em] text-background/50">Kontakt</p><p className="text-sm leading-7">Brienner Straße 12<br />80333 München<br />+49 89 123 45 67<br />hallo@nordhaus.immo</p></div><div><p className="mb-4 text-xs uppercase tracking-[0.2em] text-background/50">Rechtliches</p><div className="flex flex-col gap-3 text-sm text-background/70"><a href="#">Impressum</a><a href="#">Datenschutz</a><a href="#">AGB</a></div></div></div><div className="mx-auto flex max-w-7xl justify-between border-t border-background/15 px-6 py-5 text-xs text-background/45 lg:px-10"><span>© 2026 Nordhaus Immobilien</span><span>Mitglied im IVD</span></div></footer> }

export function PropertyCard({ property, onOpen }: { property: typeof properties[number], onOpen?: () => void }) { return <article className="group"><button onClick={onOpen} className="block w-full text-left"><div className="relative aspect-[4/3] overflow-hidden bg-muted"><img src={property.image} alt={property.title} className="size-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 bg-background px-3 py-1 text-[10px] uppercase tracking-[0.18em]">{property.type}</span></div><div className="flex items-start justify-between gap-3 pt-4"><div><h3 className="font-serif text-xl">{property.title}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-3.5" />{property.location}</p></div><p className="text-sm font-medium">{property.price}</p></div><div className="mt-3 flex gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-1"><BedDouble className="size-3.5" />{property.rooms} Zimmer</span><span className="flex items-center gap-1"><Ruler className="size-3.5" />{property.area} m²</span></div></button></article> }

export function ExposeModal({ property, close }: { property: typeof properties[number], close: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`Exposé ${property.title}`}><div className="max-h-[90vh] w-full max-w-4xl overflow-auto bg-background"><div className="grid md:grid-cols-[1.05fr_0.95fr]"><div className="relative aspect-square md:aspect-auto"><img src={property.image} alt={property.title} className="size-full object-cover" /><button onClick={close} aria-label="Exposé schließen" className="absolute right-4 top-4 flex size-9 items-center justify-center bg-background"><X className="size-4" /></button></div><div className="flex flex-col p-7 lg:p-10"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Exposé · {property.type}</p><h2 className="mt-4 font-serif text-4xl leading-tight">{property.title}</h2><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4" />{property.location}</p><p className="mt-8 text-2xl">{property.price}</p><div className="my-8 grid grid-cols-2 gap-4 border-y border-border py-5 text-sm"><span>{property.rooms} Zimmer</span><span>{property.area} m² Wohnfläche</span><span>Bezug: sofort</span><span>Energie: A+</span></div><p className="text-sm leading-6 text-muted-foreground">Eine außergewöhnliche Adresse für alle, die Architektur, Licht und urbane Ruhe miteinander verbinden möchten.</p><Button className="mt-auto w-full rounded-none py-6" onClick={() => alert('Vielen Dank. Wir melden uns persönlich bei Ihnen.')}>Interesse bekunden <ArrowRight data-icon="inline-end" /></Button></div></div></div></div> }

export function ContactModal({ close }: { close: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Gespräch vereinbaren"><div className="w-full max-w-lg bg-background p-8 lg:p-10"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Persönlich für Sie</p><h2 className="mt-3 font-serif text-3xl">Lassen Sie uns sprechen.</h2></div><button onClick={close} aria-label="Schließen"><X className="size-5" /></button></div><div className="mt-8 flex flex-col gap-4"><input className="border border-input bg-transparent px-4 py-3 text-sm outline-none focus:ring-1 focus:ring-ring" placeholder="Ihr Name" /><input className="border border-input bg-transparent px-4 py-3 text-sm outline-none focus:ring-1 focus:ring-ring" placeholder="E-Mail-Adresse" type="email" /><textarea className="min-h-28 border border-input bg-transparent px-4 py-3 text-sm outline-none focus:ring-1 focus:ring-ring" placeholder="Worum geht es bei Ihnen?" /><Button className="rounded-none py-6" onClick={() => { alert('Danke, wir melden uns innerhalb eines Werktages.'); close() }}>Anfrage senden <ArrowRight data-icon="inline-end" /></Button></div></div></div> }

export function TrustStrip() { return <div className="grid border-y border-border md:grid-cols-4">{['15+ Jahre Marktführer','Ø 38 Tage Vermarktungszeit','100% Diskrete Abwicklung','IHK-Zertifizierte Sachverständige'].map((item) => <div key={item} className="border-border px-5 py-6 text-center text-xs uppercase tracking-[0.12em] md:border-r last:border-r-0">{item}</div>)}</div> }

export function SectionEyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">{children}</p> }

export function ValuationSteps({ onComplete }: { onComplete: (value: string) => void }) { const [step, setStep] = useState(1); const [type, setType] = useState('Einfamilienhaus'); const [area, setArea] = useState(180); const [plz, setPlz] = useState(''); return <div className="border border-border bg-background p-6 lg:p-8"><div className="mb-8 flex items-center justify-between"><div><SectionEyebrow>Ihre erste Einschätzung</SectionEyebrow><p className="mt-2 font-serif text-2xl">In 3 Schritten zum Marktwert.</p></div><span className="text-sm text-muted-foreground">0{step} / 03</span></div>{step === 1 && <div className="grid grid-cols-2 gap-3">{['Einfamilienhaus','Eigentumswohnung','Mehrfamilienhaus','Grundstück'].map(x => <button key={x} onClick={() => { setType(x); setStep(2) }} className="border border-border p-4 text-left text-sm transition hover:border-foreground">{x}<ChevronRight className="mt-3 size-4 text-muted-foreground" /></button>)}</div>}{step === 2 && <div><label htmlFor="area" className="flex justify-between text-sm"><span>Wohnfläche</span><strong>{area} m²</strong></label><input id="area" type="range" min="50" max="450" value={area} onChange={e => setArea(+e.target.value)} className="mt-8 w-full accent-foreground" /><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>50 m²</span><span>450 m²</span></div><Button onClick={() => setStep(3)} className="mt-8 w-full rounded-none">Weiter <ArrowRight data-icon="inline-end" /></Button></div>}{step === 3 && <div><label htmlFor="plz" className="text-sm">Lage oder PLZ</label><input id="plz" value={plz} onChange={e => setPlz(e.target.value)} placeholder="z. B. 80333 München" className="mt-3 w-full border border-input bg-transparent px-4 py-3 outline-none focus:ring-1 focus:ring-ring" /><Button onClick={() => onComplete(`type=${encodeURIComponent(type)}&area=${area}&plz=${encodeURIComponent(plz)}`)} className="mt-4 w-full rounded-none">Analyse starten <ArrowRight data-icon="inline-end" /></Button></div>}</div> }

export const CheckItem = ({ children }: { children: React.ReactNode }) => <li className="flex gap-3 text-sm leading-6"><Check className="mt-1 size-4 shrink-0" />{children}</li>
export const ContactLine = () => <div className="flex flex-wrap gap-5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Phone className="size-4" />+49 89 123 45 67</span><span className="flex items-center gap-2"><Mail className="size-4" />hallo@nordhaus.immo</span></div>
export const MenuIcon = Building2
